### ISSUE TITLE
How contributors can help?

### ISSUE THREAD

**Issue by Paxa** [14bits/voik#3]
I'm very excited about this project, as alternative to kafka without java

How contributors can help?

**Comment by marceloboeira** [comment]
Thanks for the issue @Paxa. I'll make sure to move the roadmap here later today, so that we can discuss and assign people to tasks.

**Comment by marceloboeira** [comment]
@Paxa @zoonage as promised, I've spared some time to move the backlog/roadmap here. 

We have now, #7 which is an "epic" milestone, containing all the related issues for version 0.1.0, a very shallow but functional MVP. #8 / #4 / #5 are issues that need attention asap so we can move forward. 

Feel free to add your considerations, and let me know if there is anything else that would help you to catch up more easily.

**Comment by marceloboeira** [comment]
I've also created a contributors guide now. check it here https://github.com/14-bits/voik/blob/master/docs/CONTRIBUTING.md and also if you want to learn more about the architecture please check here: https://github.com/14-bits/voik/blob/master/docs/ARCHITECTURE.md

**Comment by jaywalker76** [comment]
Hello @marceloboeira . I'd like to help out, though I'm completely new to Rust. However, I see this as a great opportunity and would like to take part.

**Comment by marceloboeira** [comment]
@jaywalker76 I'm pretty new to rust myself, that's not an issue. You can take a look at the issues around, or find things that you believe are important (for documentation/tooling).
